### PR TITLE
Fix check for the type HTMLVideoElement

### PR DESCRIPTION
**Pull request by ti777777**

### CODE REVIEW

**Comment by ti777777** [comment]
#525

**Comment by ti777777** [comment]
Hi,
Does anybody can help to review this PR

**Review by mmalomo — APPROVED** [review]

**Comment by mageshkumar1598** [comment]
@mmalomo Any idea when this will be merged to the master?

**Comment by ti777777** [comment]
> @mmalomo @ti777777 Any idea when this will be merged into the master?

Sorry,I am not the maintainer. I have no idea.😅

**Comment by mageshkumar1598** [comment]
A temporary hack worked for me.

`const img = document.getElementById('img');`
`img.videoWidth = 0;`
`codeReader.decodeFromImage(img).then((result) => {
//Logic goes here
}`

**Comment by werthdavid** [comment]
I fixed it directly on master

**Pull request closed without merging**
