### PR TITLE
[Feature] Support for CODABAR code (#194)

### PR DESCRIPTION
**Pull request by dodobelieve**
[Feature] Support for CODABAR code (#194)

### CODE REVIEW

**Comment by odahcam** [comment]
Someday I will rule this bot.

**Comment by odahcam** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/core/oned/MultiFormatOneDReader.ts  1
- src/core/oned/CodaBarReader.ts  7
- src/test/core/oned/CodaBarBlackBox1.spec.ts  1
- src/core/common/BitArray.ts  10
- src/test/core/common/BitArray.spec.ts  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/zxing-js/library/pullRequest?prid=6382149&bid=20701372)

**Comment by thorin8k** [comment]
Nice work! 

Is this planned to be in the next release? 

Thanks

**Review by werthdavid — APPROVED** [review]

**Comment by werthdavid** [comment]
@dodobelieve can you resolve those conflicts? I will merge it then

**Pull request merged**
