### PR TITLE
Add alternative data matrix detector

### PR DESCRIPTION
**Pull request by NilsEngelbach**
Hello,

I wanted to contribute an possible improvement for the data matrix code detection by porting a different algorithmn from the zxing-cpp project. Instead of using the `WhiteRectangleDetector` it searches for two lines building the L in the code. I managed to port the code, and tested it manually. But sadly i was not able to run the test, or to add tests to compare the performance of the two detectors, to verify that it will be an improvement.

The command `yarn test` throws many errors on the current master branch, should it be working?

https://github.com/nu-book/zxing-cpp/blob/2ceda95cba943b3b2ab30af3c90150c97e84d416/core/src/datamatrix/DMDetector.cpp#L442-L1072

### CODE REVIEW

**Comment by Swiftwork** [comment]
Hi @NilsEngelbach, thank you for your contribution! We are working on correcting the testing, but most of that happens in the develop branch. However, I think the DataMatrix tests might still need to be looked at. Redirect this PR there and try to see if you can get them running using the newer code.

**Comment by NilsEngelbach** [comment]
@Swiftwork Thanks for the quick response, develop looks much better! I will close this PR and open a new one, as soon as i can confirm an actual improvement in the detection.

**Comment by Swiftwork** [comment]
You don't need to close the PR, just change the target :)

**Comment by odahcam** [comment]
@NilsEngelbach just to give a tip, I use to always create a new entry on `.vscode/launch.json` like:

```json
    {
      "type": "node",
      "request": "launch",
      "name": "Multi-reader Tests - ts-node",
      "program": "${workspaceFolder}/node_modules/mocha/bin/_mocha",
      "args": [
        "--require",
        "ts-node/register",
        "--require",
        "tsconfig-paths/register",
        "-u",
        "tdd",
        "--timeout",
        "999999",
        "--colors",
        "--recursive",
        "./src/test/core/multi/**/*.spec.ts"
      ],
      "internalConsoleOptions": "openOnSessionStart"
    }
```

...where you can filter which tests you want to run on the property `"args"` last entry. Or, of course, you can simply create the same command in the command line you prefer and run it, it will work as well.

**Pull request closed without merging**
