### PR TITLE
[WIP] Port Aztec 2D Readers

### PR DESCRIPTION
**Pull request by odahcam**

### CODE REVIEW

**Comment by unknowndomain** [comment]
It seems like reading here that Aztec Reading is working, I was wondering what is holding up releasing this, I'd like to play with it, but couldn't get the current version of the branch to compile but I am not a typescript person so could be me, installed all the bits and eventually ran npm run build and errors, so then I couldn't test the version in the branch.

**Comment by odahcam** [comment]
I don't think it's working, since I couldn't even make the tests to pass. It could be some error in the tests itself, but I don't know. The only thing I'm sure is that this code is not production ready.

**Comment by unknowndomain** [comment]
@odahcam I've asked a new member of my team @EggOetgen to have a look into where the Aztec reading feature in this project is at and what it would take to get it production ready.

We'd like to use the Aztec scanning in one of our team's projects an open source asset management tool we built and use.

I'll wait to see what he comes back with but if it's something we can support you on to that would be great, my team is mostly focused on students at the moment, but in the next couple of weeks that will end and we'll have time to work on other projects.

**Comment by 10eputzen** [comment]
is there a way to test this with the ngx-scanner?

**Comment by zugende** [comment]
@odahcam Really looking forward for Aztec support! Thanks for your work.

**Comment by odahcam** [comment]
Thank you very much. Right now I'm finishing my bachelor so it will take some time 'till I back to this, sorry for the bad news.

**Comment by zugende** [comment]
Hi @odahcam hope you bachelor thesis is coming along fine. Can you give a super rough timing idea of when this PR will be merged? :)

**Comment by odahcam** [comment]
Hey! Unfortunately I don't pretend to work on this PR anytime soon. 🙁

**Comment by alexcondrea** [comment]
Hey, would it be ok if I'd implement only the decoder/reader on a different branch and create a pull request from that? Implementing/porting everything is a lot of work and I think for most people the decoder is what they are interested in, at least the app developers.

**Comment by odahcam** [comment]
That would be great! This PR is about the decoder BTW, that's why it's called "Port ... **Reader**", hehe. You can fork this branch and continue the work in here, pretty much has already been done.

**Comment by MartyHav** [comment]
Hi I am working on it as well. 
@odahcam I can see some differences in the aztec Detector in comparison to the java origin.
For example:  
JS
https://github.com/zxing-js/library/blob/d904959cb2d7df13606e8b22584fccc90ff1b361/src/core/aztec/detector/Detector.ts#L400-L425
Java
https://github.com/zxing/zxing/blob/459c0197a7ce16ba9d2ce8d7acac2169a87fe066/core/src/main/java/com/google/zxing/aztec/detector/Detector.java#L358-L360

I just wonder cause  all the code looked quite identical so far. 
Do you know if this intended and the reasons behind that?

**Comment by odahcam** [comment]
@MartyHav it's a very good observation, I have no ideia. The developer must have confused the code with something else or was going trough some testing, I really don't know. I think you should try using the [java implementation](https://github.com/zxing/zxing/blob/459c0197a7ce16ba9d2ce8d7acac2169a87fe066/core/src/main/java/com/google/zxing/aztec/detector/Detector.java#L359) to see what happens.

**Comment by MartyHav** [comment]
@odahcam yes, seems the way to go. Thanks for the quick response.

**Comment by odahcam** [comment]
You're welcome.

**Comment by mneuber** [comment]
did work, created PR
https://github.com/zxing-js/library/pull/294 
( aka MartyHav )

**Comment by odahcam** [comment]
I'm closing this due to the new PR.

**Pull request closed without merging**
