### PR TITLE
Add support for RSS14 codes

### PR DESCRIPTION
**Pull request by aryahz**
Following up on https://github.com/zxing-js/library/issues/80.

We've been developing a barcode scanner using the library and have converted the RSS-14 reader classes. Enabling support for the following RSS-14 formats:

DataBar Omnidirectional
DataBar Stacked Omnidirectional
DataBar Truncated
DataBar Stacked

### CODE REVIEW

**Comment by aryahz** [comment]
Thanks for reviewing, I'll sort out the codacy warnings and look into unit tests. 

I believe the missing format for RSS-14 is RSS/DataBar Limited, I ran out of time to get that one working, am not certain it works with the original Zxing library, although not certain. 

Please note we've not worked on the RSS Expanded format reader. We've raised a CR for it but not going to implement that in the short term.

**Comment by odahcam** [comment]
No problem @aryahz , this source is already a lot, I will try to help with something if I find time.

**Comment by odahcam** [comment]
Waiting for the CI to update the statses. Do you think it's ready for a merge?

**Comment by odahcam** [comment]
Nice, I won't wait for Codacy, looks like it's dead.

**Comment by aryahz** [comment]
Excellent, thanks for merging.

**Comment by odahcam** [comment]
Thank you for sharing this, I will be releasing this ASAP.

**Comment by ilinkMat** [comment]
Any update on when this will be released ?

**Comment by odahcam** [comment]
Planned for 2018-12-11.

**Comment by odahcam** [comment]
@aryahz the tests aren't passing, could you make a little investigation?

**Comment by aryahz** [comment]
I see, the tests aren't passing through the test build. The barcodes are scanning successfully manually using our scanner, so the reader code is working. I'll investigate today and will fix the tests ASAP.

**Comment by aryahz** [comment]
I've committed a fix. I hadn't yet included the RSS14Reader in the MultiFormatOneDReader class. It's there now and the tests run successfully.

**Comment by odahcam** [comment]
I thought it was already there, so it don't even come to my mind. 😆

**Comment by aryahz** [comment]
I thought I had already updated it, but when merging another branch with our internal code repository I missed that class. We don't actually use MultiFormatOneDReader so we hadn't picked up on it, until now.

If you can manually copy it in that will be great, as it's just a single file change. The file is here:
https://github.com/aryahz/library/blob/master/src/core/oned/MultiFormatOneDReader.ts

**Comment by odahcam** [comment]
All right, doing that. Thanks!

**Pull request merged**
