### PR TITLE
Remove const from enum BarcodeFormat

### PR DESCRIPTION
**Pull request by jojastahl**
This is needed to support easy string barcode format parsing in zxing-js/ngx-scanner#112.

### CODE REVIEW

**Comment by jojastahl** [comment]
Can't see any value change in `BarcodeFormat`. Can you give me precise location? I only see one line changed removing const.

**Comment by odahcam** [comment]
That's exactly why I'm asking that question. hahua

Why shouldn't it be a `const`?

**Comment by jojastahl** [comment]
See https://www.typescriptlang.org/docs/handbook/enums.html. Near the articles end there is a section on const enum.

Basically:
```typescript
const enum ConstEnum { a, b, c }
enum NonConstEnum { a, b, c }

let str = 'a';
let constEnumVal = ConstEnum[str];  // compile time error
let enumVal = NonConstEnum[str];  // ok: enumVal === NonConstEnum.a
```

The `NonConstEnum[str]` style translation of the string enum value to the underlying numeric value is needed in zxing-js/ngx-scanner#112 to translate string barcode format name to BarcodeFormat enum value.

**Comment by odahcam** [comment]
I'm not sure if it is concern of this source, I think it's more appropriate to write a new enum on the scanner. 🤔

**Comment by jojastahl** [comment]
OK, but you and @werthdavid asked me in zxing-js/ngx-scanner#112 to use the `BarcodeFormat` directly from the library, so I adjusted zxing-js/ngx-scanner#112 to do so. The downside of declaring a new enum or whatsoever in the scanner is, that it has to be kept in sync with the library's `BarcodeFormat` enum.

**Comment by odahcam** [comment]
Can't say how I hate these taff decisions, but you are right. Let's make this little guy here not a `const` and keep on 👁 on it to see how it behaviors. Thanks.

**Pull request merged**
