### PR TITLE
performance improvement for canvas

### PR DESCRIPTION
**Pull request by My6UoT9**
see https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Optimizing_canvas#Turn_off_transparency

### CODE REVIEW

**Comment by odahcam** [comment]
What happens to the alpha channel? Is it inked with some other color?

**Comment by My6UoT9** [comment]
I have not tested that, the input I have is a video stream - since that has no transparency I did not care about it. I think it would be quite a special case to have a code in an image with transparency.

**Comment by odahcam** [comment]
Some generators, as ZXing also does, generates the code with no background by default. I think those kind of images may not work as expected when eliminating the alpha channel, because it has to be inked with some other color and this color may be the same color as the code. We should try to find a way to make this a configurable option, specially for video streams or direct camera images, that does not have a alpha channel.

**Comment by My6UoT9** [comment]
Unexpected, as far as I know most image types have a channel for transparency, so a transparent pixel has a color and a transparency. If transparency is ignored the color is used. Often its black cause its 0.

Making this configurable seems the best option; maybe along with TRY_HARDER option and other possible configurations .

**Comment by odahcam** [comment]
Hey, I gonna close this now because it became kinda invalid with the new updates. Thanks for the contrib.

**Pull request closed without merging**
