### PR TITLE
ci: test Node.js 8, 10 and 11

### PR DESCRIPTION
**Pull request by DanielRuf**
We should test all current LTS branches to make sure that these work.

### CODE REVIEW

**Comment by DanielRuf** [comment]
> error joi@13.4.0: The engine "node" is incompatible with this module. Expected version ">=8.9.0".

We should probably make this clear in the `engines` field.

**Comment by odahcam** [comment]
This remembers me that we gotta speed up our tests, they are taking too many time to run on Travis. Luckily Travis doesn't charge by time usage.

**Comment by DanielRuf** [comment]
Ah so you mean the caches? Wait a moment.

**Comment by odahcam** [comment]
Yeah! Thanks! 

However, the tests themselves need some rewriting to be improved, we were using `async` lib which made our tests very fast for a while, but it kept creating trouble, so I removed it and now most of the tests use `async`/`await`, that I wrote in a time I didn't master it, so the async code is not the best, neither the test code once I'm not that good in testing too.

**Comment by DanielRuf** [comment]
I guess tap and jest can run them in parallel (afaik).

> Jest parallelizes test runs across workers to maximize performance.

**Comment by odahcam** [comment]
That's definitely something to look in the near future, specially for the browser layer, where I'm trying to choose between Protractor and Cypress as the test framework.

**Comment by DanielRuf** [comment]
> Cypress

Afaik this is Electron and quite big.
We can use the firefox and chrome addons on Travis CI.

But let's check this (the exact testing stack and libraries) in another issue and find the best solution (karma, puppeteer, jest, ...).

**Comment by odahcam** [comment]
Thanks @DanielRuf , can I cc you in future issues about that so we can further discuss about it?

**Comment by DanielRuf** [comment]
Sure.

**Pull request merged**
