### PR TITLE
Port PDF 417 Reader

### PR DESCRIPTION
**Pull request by odahcam**

### CODE REVIEW

**Comment by progikusok** [comment]
@odahcam Hi!

Thank you for your work! 
Could you please share your approximate release date?

Thanks in advance!)

**Comment by odahcam** [comment]
Hey @progikusok since I don't know when this will be release, I only work here on my free time, since I don't get a buck for all the work here it's hard to use working hours. Currently we have 3 PRs open with 3 different port, all three needs help from the community to get merged because I won't be able to finish all they by my own.

**Comment by odahcam** [comment]
Thank you so much @franbueno and thanks for who's supporting us or wating this.

Unfortunately we still have to make 13 tests pass:

```
  195 passing (7m)
  13 failing
```

And since my last commit we got not even 1 contribution here, so we're not that good on speed.

I know this is a much requested feature and that's why I started to port this module myself, I usually don't do that, but I had to stop it to get back working on the library structure and other layers that is what I usually do.

Due to the coplexity of this port and the amount of new stuff I had to develop I spent a lot of time on this and I'm counting on any help to finish it as soon as possible, otherwise I won't be able to finish this or maybe even the next month.

**Comment by franbueno** [comment]
Thank you so much @odahcam for this feedback.  I will be expecting miracles to see this feature soon :). Thanks again!

**Comment by SaheliRoy** [comment]
Hey @odahcam, 
Great job with this,
waiting for the PR to be merged

**Comment by franbueno** [comment]
hey @odahcam, any news? :)

**Comment by odahcam** [comment]
No news, sorry.

**Comment by shaunmauer** [comment]
@odahcam - Do you have an approximate release date, seen some recent activity on this PR..

Much appreciated.

Regards,
Shaun

**Comment by shkarab** [comment]
I was trying to run the tests on your PR but it's failed, is that anything wrong in your PR or this happening in my side?

**Comment by odahcam** [comment]
This PR tests were never successful, that's because it didn't got merged yet.

**Comment by shkarab** [comment]
Oh ok thanks, but any plans for that?

**Comment by odahcam** [comment]
Nope, sorry.

**Comment by xenophilicibex** [comment]
This is herculean effort and incredibly impressive. Wish you the very best @odahcam .

**Comment by odahcam** [comment]
Thanks so much @xenophilicibex .

**Comment by odahcam** [comment]
No bot, don't. Thanks.

**Comment by odahcam** [comment]
We now have the first test passing, there's still a lot to do, but we're getting there.

**Comment by odahcam** [comment]
Hey @github-actions, I'm back!

**Pull request merged**
