### PR TITLE
Port current version of RSSExpandedReader to javascript

### PR DESCRIPTION
**Pull request by opl-**
Based on [zxing commit 2dfb2054af1e1872ac5354e6d8218931fb88e021](https://github.com/zxing/zxing/commit/2dfb2054af1e1872ac5354e6d8218931fb88e021).

Finished porting all the code. Incorporated the following fixes: zxing/zxing#1680 zxing/zxing#1692 zxing/zxing#1693 (By manually comparing the existing javascript implementation with the java code).

Didn't attempt running it yet, but all the remaining Java code got ported, including some logic which depended on the values being integers.

Related: #80

### CODE REVIEW

**Comment by opl-** [comment]
Another batch of changes. Can rebase later.

- Removed type from catch blocks (`} catch (ex: any) { ` -> `} catch (ex) {`)
- Fixed `AI01decoder` still incorrectly performing pad checks by depending on int division behavior which doesn't exist in JavaScript.
- Turned `startEnd` into a tuple type.
- Ported `RSSExpandedInternalTestCase`.
- Fixed missing `splice`/`subList().clear()`.
- Correctly implemented `removePartialRows()` and `isPartialRow()`
- Fixed integer divisions returning floats.
- Fixed `System.arraycopy` smearing the same value over the entire array (by copying a value into the position it was about to read from).
- Fixed `ExpandedRow.isEquivalent` returning false if both arrays are empty (my bad).
- Fixed `ExpandedRow` constructor not making a copy of received `pairs` list.
- Ported `RSSExpandedStackedInternalTestCase`.
- Fixed decoders calling `StringBuffer.append` with a number, resulting in the value being interpreted as a code point instead of a sequence of numbers.
- Fixed more hidden integer divisions returning floats (forgot to look for the `/=` operator).

**Comment by opl-** [comment]
Was missing one integer division and accidentally swapped a condition during minor refactoring.

Anyway, it works. There are still 4 try harder tests failing in `RSSExpandedStackedBlackBox2`, but I have no energy to even attempt to tackle that.

Not rebasing/squashing in case it makes a review easier. It probably won't.

**Review by werthdavid — APPROVED** [review]

**Comment by werthdavid** [comment]
Some tests are still failing

**Comment by opl-** [comment]
I assume you're talking about the ones mentioned [here](https://github.com/zxing-js/library/pull/630#issuecomment-2499070081). Those try to read barcodes laid out vertically, and so need `SharpImageLuminanceSource` to correctly implement the rotation functions. I believe `SharpImage*` is only used for unit tests, so this shouldn't be a problem in normal operation.

**Pull request merged**
